<?php

namespace AppBundle\Repository;

/**
 * ChamadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChamadoRepository extends \Doctrine\ORM\EntityRepository
{
	/*public function findAllChamados()
	{
		$$em = $this->getEntityManager();
        //$qb = $em->createQueryBuilder();
		$query = $em->createQuery("SELECT c, cl	FROM AppBundle:Chamado c JOIN c.cliente cl");
        qb->select('c,cl')
        ->from('AppBundle:Chamado', 'c')
        ->Join('c.clienteId', 'cl')
        ->orderBy('c.id', 'DESC');
        //dump($qb->getQuery());die;
        return $query;
	}*/
}
